### ISSUE TITLE
Feature request for Online: true

### ISSUE THREAD

**Issue by GAMECRIS** [mxve/plutonium-server-list#20]
Feature request:
I wanted to ask if it's possible to add "online: true" to the JSON query for the XLabs and Boiii servers.

I'm using a script to fetch the server information using plutools on my website. It should display the server as online, but since "online: true" is missing, the servers are shown as offline.

It would be really cool if you could inquire about the possibility of adding this feature. I would appreciate it. Thank you in advance.
![Screenshot 2023-05-02 182520](https://user-images.githubusercontent.com/88902413/235729920-519b9886-9bbb-4447-804e-345e27a2c990.png)

**Comment by mxve** [comment]
Done https://github.com/mxve/plutonium-server-list/commit/649b0032e2cc4cda84075057cfb09421dcc4fcaf
